library(ggplot2)

curr_dir <- getwd()
setwd('/data/sda_output_data/sgd_flavours')
both_layers <- read.csv('both_models.csv')

levels(both_layers$group) <- c("3 Layers","4 Layers")
levels(both_layers$method) <- c("Adagrad", "Adagrad WD","CM","NAG")

full_p <- ggplot(both_layers, aes(epoch,score, colour = method))
full_p <- full_p + geom_point(alpha = 1/6)
full_p <- full_p + scale_x_discrete(limits = c(1,300), breaks = seq(0,300,by=10))
full_p <- full_p + scale_y_continuous(limits = c(100,700))
full_p <- full_p + facet_wrap( ~ group)
full_p <- full_p + stat_smooth()
full_p <- full_p + theme(strip.text.x = element_text(size = 13))
full_p <- full_p + theme(axis.text.x = element_text(size = 13, face = "bold"))
full_p <- full_p + theme(axis.title.x = element_text(size = 13, face = "bold"))
full_p <- full_p + theme(axis.text.y = element_text(size = 13, face = "bold"))
full_p <- full_p + theme(axis.title.y = element_text(size = 13, face = "bold"))
full_p <- full_p + theme(legend.text = element_text(size = 13))
full_p <- full_p + theme(legend.title = element_text(size = 13))
full_p <- full_p + labs(colour = "SGD Method")
full_p <- full_p + ggtitle("Validation score vs epoch: optimization algorithms")
full_p <- full_p + theme(plot.title = element_text(size=15, face = "bold"))
full_p
